### PR TITLE
scoreboard & course creation fixes; fixes #107, fixes #108

### LINKED ISSUE #107: V5.0 - issue with Scoreboard on pre-1.13 servers
NoSuchMethodError on pre-1.13 servers when joining a course with scoreboard enabled.

The RegisterNewObjective method has changed on 1.13 (extra argument). To be compatible with <1.13 servers, need to use the deprecated RegisterNewObjective method.

### LINKED ISSUE #108: V5.0 - can't create checkpoint on newly created course
After running "/pa create (course)", the command "/pa checkpoint" returns a course does not exist message. The course list is not updated when a new course is created.

### PR DESCRIPTION
**Pull request by steve4744**
Downgraded registerNewObjective to pre-1.13 (deprecated) version, so that scoreboards work on 1.12.2 and below.
Made the "not completed yet" string comply to the 16 char max for scoreboards on pre-1.13 servers.
Fix course creation bug introduced by 070d9a9.

### CODE REVIEW

**Comment by A5H73Y** [comment]
Great work, thanks Steve! 👍
